case_number = 3
part_ID = 12
export_directory = "path/to/saving/dir"
ensight.variables.evaluate("OSI_MEAN = SpaMean(plist,OSI,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("TAWSS_MEAN = SpaMean(plist,TAWSS,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("RRT_MEAN = SpaMean(plist,RRT,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("TAWSS_MAX = Max(plist,TAWSS,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("OSI_MAX = Max(plist,OSI,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("RRT_MAX = Max(plist,RRT,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("TAWSS_MIN = Min(plist,TAWSS,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("OSI_MIN = Min(plist,OSI,[],Compute_Per_case)")
ensight.part.select_begin(part_ID)
ensight.variables.evaluate("RRT_MIN = Min(plist,RRT,[],Compute_Per_case)")
ensight.variables.select_byname_begin("TAWSS_MEAN","TAWSS_MIN","TAWSS_MAX","OSI_MEAN","OSI_MIN","OSI_MAX","RRT_MEAN","RRT_MIN","RRT_MAX")
ensight.solution_time.current_step(6.0)
ensight.solution_time.update_to_current()
ensight.variables.save_constants("csv","1","1",export_directory + "/EnSightExport","case"+str(case_number)+".csv")