%% INFLOW WAVEFORM FITTING SCRIPT
% v1 - A.Vignolo - Nov 2023 - First implementation.
% v2 - A.Vignolo - Mar 2024 - No iteration is actually needed to determine
%                             the SF, this has been simplified.
%
% This script preprocesses the inlet flow time waveform for bloodflow
% simultions in a pulsatile regime. A raw datafile containing a time series
% of the inlet flow (e.g. obtained from a plot in a reference) is loaded,
% and its Fourier series approximation is computed up to a arbitrary number
% of terms.
%
% After obtaining a base waveform, the reference function is adjusted to
% match patient specific information. First, the period is scaled to match
% each of the patients HR, and then the whole function is scaled by means
% of a multiplicative factor to match an estimated Stroke Volume for each
% patient.
clc;
clearvars;

%% Define input parameters and some options
% Manually check that the path for the input data file, the sheet names,
% and the selected ranges match the structure of your case. Check the
% 'Import data' section within this script.

% Define how many modes are to be consiered for fitting the base waveform
nTerms = 20;
% Define the fraction of the stroke volume that is diverted before reaching
% the simulation domain. E.g. 0.25 according to Moore & Ku (1994).
divFrac = 0.25;

%% Import data
% The reference waveform points (in s and m3/s) needs to be loded into the
% refInletWave table, with names 'Time' and 'Qin'.
%
% Case name for each patient, systolic and diastolic pressure (in mmHg),
% heart rate (in bpm) and haematocrit fraction need to be loaded into the
% clinicalData table, where each row corresponds to a patient and the
% variable names are 'Case', 'SP', 'DP', 'HR' and 'phi.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%% LOAD YOUR DATA HERE %%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% Fit the coefficients for the Fourier series of the reference function
% This section will compute the signal's Fourier series using its Discrete
% Fourier Transform (DFT), which in turn is computed by means of the Fast
% Fourier Transform (FFT), already implemented in Matlab.

% Resample the raw data in therms of the mean sample rate. If not, the FFT
% algorithm may have some problems.
    % Define new time vector (it is important that this is an even number)
    t_uniform = linspace(refInletWave.Time(1),refInletWave.Time(end),200);
    % Interpolate data
    y_uniform = interp1(refInletWave.Time, refInletWave.Qin, t_uniform, 'linear', 'extrap');

% Compute the Fourier coefficients of the resampled signal
    % Compute the FFT of the uniform data series
    Y_uniform = fft(y_uniform);
    % Number of points
    N = length(y_uniform);
    % Extract independent term and sine and cosine components
    a0 =           Y_uniform(      1)  / N;
    an =  2 * real(Y_uniform(2:N/2+1)) / N;
    bn = -2 * imag(Y_uniform(2:N/2+1)) / N;

%% Produce check plot
% Compute the Fourier series approximation
    % % % % Initialize series with the independent term
    % % % % y_approx_uniform = a0;
    % Define the cardiac cycle period
    T_cycle = max(t_uniform);
    % Compute the angular frequency of the signal
    vo = 2*pi/T_cycle;
    % Compute the approximated waveform
    y_approx_uniform = a0 + cos(kron(t_uniform',(1:nTerms)*vo))*an(1:nTerms)' ...
                          + sin(kron(t_uniform',(1:nTerms)*vo))*bn(1:nTerms)';

% Set default interpreter for plots
set(groot,'defaulttextinterpreter','latex');  
set(groot,'defaultAxesTickLabelInterpreter','latex');  
set(groot,'defaultLegendInterpreter','latex');

% Display the original and resampled signals
fig_Comparison = figure('Name','Fig_seriesVsOriginalData','NumberTitle','off');
plot(refInletWave.Time, refInletWave.Qin, 'b-', 'LineWidth', 2, 'MarkerSize', 2);
hold on
plot(t_uniform, y_approx_uniform, 'r--', 'LineWidth', 2, 'MarkerSize', 2);
hold on
xlabel('Time (s)','FontSize',12);
ylabel('Flow (m$^3$/s)','FontSize',12);
xlim([0,T_cycle])
ax = gca;
ax.TickLabelInterpreter = "latex";
ax.FontSize = 12;
grid on
legend({'Reference waveform','Fourier series approximation'},'Interpreter','latex','FontSize',12)

%% Produce output textfile with the analytical waveform obtained
fileID = fopen(sprintf('%s.txt',mfilename),'w');
fprintf(fileID,'----- PROGRAM EXECUTION START: %s - %s ------------------------------------------------------------------\n',mfilename,datetime);
fprintf(fileID,'This has been automatically generated at timestamp %s, while executing %s\n',datetime,mfilename);
fprintf(fileID,'This output reports the base waveform approximation for an inlet boundary condition.\n');
fprintf(fileID,'\t This preprocessing tool has been generated by Andrés Vignolo, see documentation for more details.\n\n');

% Print independent term
fprintf(fileID,'a0 = %.7E [m^3 s^-1]\n',a0);
% Loop and print coefficients
for iMode = 1:nTerms
    fprintf(fileID,'a%d = %.7E [m^3 s^-1]\n',iMode,an(iMode));
    fprintf(fileID,'b%d = %.7E [m^3 s^-1]\n',iMode,bn(iMode));
end
fprintf(fileID,'inletflow = a0');
for iMode = 1:nTerms
    fprintf(fileID,'+a%d*cos(v0*t)+b%d*sin(v0*t)',iMode,iMode);
end
fprintf(fileID,'\n\n----- PROGRAM EXECUTION END   : %s - %s ------------------------------------------------------------------\n',mfilename,datetime);
fclose(fileID);

%% Write coefficients to an Excel file
fourierSeries = table((0:nTerms)',[a0,an(1:nTerms)]',[0,bn(1:nTerms)]',...
    'VariableNames',{'Mode','an','bn'});
writetable(fourierSeries,sprintf('%s_out.xlsx',mfilename),"Sheet",'baseFourierSeries','WriteRowNames',false);

%% Patient specific inlets
% The base waveform will be scaled in time and in amplitud, to match each
% of the patient's heartbeat and stroke volume.

% Compute heartbeat period (in s) for each patient
Tpatient = 60./clinicalData.HR;

% Compute mean pressure, according to Verrij et al (2008)
Pmean = 0.4*(clinicalData.SP-clinicalData.DP) + clinicalData.DP;

% Compute the fraction of the stroke volume reaching the domain, Vp
%   Cardiac Output is estimated via the Liljestrand & Zander formula (1940)
%   The result is corrected by the factor k proposed by Koenig et al (2015)
%   Stroke Volume is obtained by dividing by the HR
%   The fraction of the SV reching the simulation domain is estimated from
%   the diverted fraction (user input, divFrac)
%
%   The resulting equation is:
%              Vp = [(SP-DP)/(SP+DP)] * k * (1-divFrac)
%   Notice pressure should be expressed in mmHg and that the result is in
%   L. It will be converted to m3
k = 0.282; % Estimated for the whole population based on the reported data
Vp = (1-divFrac)*k*((clinicalData.SP - clinicalData.DP)./(clinicalData.SP + clinicalData.DP))/1e3;

% Initialize a table for holding estimations and results for each patient
aux1 = zeros(size(clinicalData,1),1);
patientResults = table(clinicalData.Case,Tpatient,Pmean,Vp,aux1,...
    'VariableNames',{'Case','T','Pmean','Vp','ScaleFactor'}  ,...
    'RowNames',clinicalData.Case);

% Compute the scale factors
patientResults.ScaleFactor = patientResults.Vp ./ (a0*patientResults.T);

% Initialize figure
fig_patientSpecific = figure('Name','Fig_patientSpecificInflow','NumberTitle','off');
legendCell = cell(1,size(clinicalData,1));

% Loop patients, adjust waveform and plot
for iPatient = 1:size(clinicalData,1)
    % Define case string
    iPatientStr = patientResults.Case(iPatient);
    % Get this patient's Scale Factor
    SF = patientResults.ScaleFactor(iPatient);
    % Get this patient's angulat frequency
    w = 2*pi/patientResults.T(iPatient);
    % Define the patient's fuction
    f = @(t) SF*(a0 + cos(kron(t,(1:nTerms)*w))*an(1:nTerms)' + sin(kron(t,(1:nTerms)*w))*bn(1:nTerms)');
    % Add to plot
    t_aux = linspace(0,patientResults.T(iPatient),200)';
    plot(t_aux*1E3, f(t_aux)*1E6, 'LineWidth', 1.5);
    hold on
    legendCell{iPatient} = iPatientStr{:};
end

xlabel('Time (ms)','FontSize',12);
ylabel('Flow (mL/s)','FontSize',12);
xlim([0,max(patientResults.T)*1E3])
ax = gca;
ax.TickLabelInterpreter = "latex";
ax.FontSize = 12;
grid on
legend(legendCell,'Interpreter','latex','FontSize',10,'NumColumns',3)

%% Write output to an Excel file
writetable([patientResults,clinicalData(:,'phi')],sprintf('%s_out.xlsx',mfilename),"Sheet",'patientResults','WriteRowNames',false);
